### ISSUE TITLE
Build Log In Form - Iteration 4

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#37]
# User Story

* The folx arriving at our original home page will be coming in with knowledge of what the mission of the app is and looking to get set up to be volunteers.  
* Our returning volunteers will see on that home page a small blurb thanking them for their interest and at the top a choice to log in or Sign up
* Once they click the Log In button they will be routed to a view where they are prompted to enter their email address, a pass word
* At the top of the page they will see the options to return to the home page 
* Just Below the input lines for their emails and passwords, they will be prompted to click the Log In button by a gentle hover highlighting
* From a successful log in, the log in page will have the ability to **_route_** to their own personalized `My Shifts` record, an opportunity to `Update Info`, and the chance to  fill out their `Pick Up Reports Form`.  
* Since these last three components are to be built out in another iteration having their psuedo code in place will suffice for this iteration

# Tasks

- [ ] Create Log In Form Component 
//Maybe this should be a container given its size and functionality - what do we think as a team?
- [ ] Verify Router Syntax between Header log in button and Log in Form Component are fully functional
- [ ] Add API fetch for POST
- [ ] Create Place holders/commented out pseudo code  for routes to Update Information form component
- [ ] Create Place holders/commented out pseudo code  for routes to My Shifts Component
- [ ] Create Place holders/commented out pseudo code for routes to Pick Up Reports Form Component
- [ ] Test new component with Cypress
- [ ] Test Routing with Cypress
- [ ] Give Code a Review and Refactor to verify that all codes present are at optimal efficiency

# Additional Notes to Reviewers
Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions!
