### ISSUE TITLE
Build Sign Up Form - Iteration 5

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#38]
# User Story

* The folx arriving at our original home page will be coming in with knowledge of what the mission of the app is and looking to get set up to be volunteers.  
* Once they click the sign up button they will be routed to a view where they are prompted to enter their email address, a pass word, and confirm password.  
* At the top of the page they will see the options to return to the home page and an option to log in
* Below the input lines for their emails and passwords, they will be prompted to click the sign up button perhaps by a gentle hover highlighting

# Tasks

- [ ] Create Sign Up Form Component
//Maybe this should be a container given its size and functionality - what do we think as a team?
- [ ] Verify Router Syntax between Header log in button and Log in Form Component are fully functional
- [ ] Test new component with Cypress
- [ ] Test Routing with Cypress
- [ ] Give Code a Review and Refactor to verify that all codes present are at optimal efficiency

# Additional Notes to Reviewers
Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions!
