### ISSUE TITLE
Build Out Individual Log In Page - Iteration 6

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#39]
# User Story 

*After a successful log in the user will be routed to their own individualized page.  
* Our user should feel welcomed with greeting, the feel of the page should be warm and inviting as much as practical.
* Next to the User's name, at the top is a button that allows a link to a new form for updating of personal information
* Below the name and update buttons, and left justified on the page:
     * There should be a list of recurring shifts called `My Shifts`, which is titled by a button.
     * A button to `Past Shifts` with a small listing below it 
     * A button to `Complete Reports` with no list 
* All three buttons link the user by click to a new component/page view with more details in each upon build

# Tasks:

- [ ] Create Individual Volunteer Component
- [ ] Verify path from Log in component to Volunteer Component is sound
- [ ] At the top right hand corner create a `Log Out` button
- [ ] Create Greeting
- [ ] Pull in Individual Name based on log in
- [ ] Create a smaller `Update Info` button
- [ ] Create a larger `My Shifts` button that auto-populates the two to three most recurring shifts below the button for the user to see
- [ ] Create a larger `Past Shifts` button that auto generates a small listing of one to two past shifts held by the user
- [ ] Next to that, and to the right, create a smaller `Pick Up Shift Reports` button
- [ ] Add API fetch for POST/PATCH
- [ ] Test new component with Cypress
- [ ] Test Routing with Cypress
- [ ] Give Code a Review and Refactor to verify that all codes present are at optimal efficiency

# Additional Notes to Reviewers

Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions... and i'm open to dm :)
