### ISSUE TITLE
Build out the Update Info Form - Iteration 7

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#40]
# User Story 

* User should be able to navigate from their individualized page to their update info page by clicking the update info button
* Upon arrival the user should be prompted by the title of the page that reads `update my info`
* At the top right they should see the option to log out of their account and at the top left they should see the option to go back a page -- this should conditionally render a note to our guest stating that they will lose any entered data if they go back a page with out clicking update
* They should see prompts to fill in their first and last names
* a check box with a question prompt that reads: Under 18? - Folx that are under 18 can still volunteer, but need a person responsible for them, with them. - So if they click this box we should have it set up that a conditionally rendered note shows up for them to route them to a new form page ( this additional form is NOT MVP)
* They should also see a chance to enter their phone number, email,  and their preferred method of contact
* They should be able to choose their preferred method of transportation type
* They should be able to answer whether or not they have a car
* There is a chance to read and sign off on reading the Robot waiver and a check box opportunity to agree to sign the waiver

# Tasks: 

- [ ] Create Initial template structure for Update Info Form Component
- [ ] Check Router syntax is fully functional from `Individual Volunteer` Component to `Update Info` button
- [ ] Top of the page should read `Update My Info`
// If There is better vernacular, we are open to this
- [ ] Top Right should have a `Log Out` button
- [ ] Top Left should have a `Back` || `Return to Previous Page` button
- [ ] Create input and Label Form Component Structure
     - [ ] `First Name`,` Last Name` input and label
     - [ ]  a **_Check Box_** for `Under 18?` should arrive on the first line
     - [ ] `Phone Number` Input and Label
     - [ ] `Email` Input and Label
     - [ ] `Preferred Contact` Label with **_Check Box_** options for `Text` or `Email`
     - [ ] `Preferred Transportation Type` Label with **_Check Box_** options for `Car`, `Bike`, || `e-bike`
     - [ ] Prompt Label that reads: Do you have a car? with the **_Check Box_** options for `yes` && `no`
     - [ ] Possible <p> tag with a link in it that reads: In order to volunteer you must read _this waiver_ . After reading the waiver, to you agree to its terms?  with the **_Check Box_** options for `yes` && `no` 
     - [ ] Ensure _this waiver_ links to waiver, or pops up waiver for user to read
- [ ] Add API fetch for POST/PATCH
- [ ] Test new component with Cypress
- [ ] Test Routing with Cypress
- [ ] Give Code a Review and Refactor to verify that all codes present are at optimal efficiency
  

# Additional Notes to Reviewers 

Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions!
