### ISSUE TITLE
Create My Shifts Page - Iteration 8

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#41]
# User Story

* User should arrive at their `My Shifts` page and see one time shifts, past shifts and recurring shifts titled and listed on the page 
* There should be a `Filter By` button that allows the user the choice of how they view their shifts
* Recurring Shifts list should appear as default first/top viewed list its button next to it should be to mark an absence
* One time shifts should appear with the option to cancel via a button to its right hand side 
* There should be a back button that takes the user to their individual user page

# Tasks:

- [ ] Create basic structure for beginning `My Shifts` Form Component
- [ ] Check Router syntax is fully functional from `Individual Volunteer` Component to `My Shifts` Component
- [ ] Top of the Page Should read, "My Shifts"
- [ ] Build a `Filter By` drop down button that offers choices to shifts display on page by `Recurring Shifts`, `Past Shifts`, && `One Time Shifts`
- [ ] Ensure drop down design is responsive to smallest screen size first, and build out bigger screens last as our users are most often on their phones
- [ ] Recurring shifts should be default top of page display if no filter choice is chosen by user
- [ ] `Recurring Shifts` label with an `absence` button to show the shift as open and in need of filling
- [ ] Recurring Shifts should list in order by date they were signed up for
- [ ] `One time Shifts` should show up with the  `cancel shift` button as an option
- [ ] 

# Additional Notes to Reviewers

Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions!
