### ISSUE TITLE
Create A Pick Up Reports Form - Iteration 9

### ISSUE THREAD

**Issue by battan40** [RosanneUssery/food-rescue-robot-v2#42]
# User Story

* User should be able to click on the complete Report button located on the bottom right hand side of the screen and navigate to a new form

* Here the User should feel welcomed by the the title `Welcome to the Pick-Up Reports Form` 

* It should be clear to the User that on this page they will state where the shift is located, what date it was performed, and exactly what they picked up :)

* They may find this easiest in a simple series of choices and small opportunities to type in info about what they picked up, and whether they they actually weighed it or are guestimating the weight of their pick up

* They will be able to leave info about how much time they spent and any additional notes for the team.  

* They will have the option to flag their entry to the administrators of the app using a check box

* When they are done filling out the form they will see at the bottom of the form a button that they can click for submission and a button that should take them home to their individual landing page

* After they click the `submit form` button they will receive a conditionally rendered message letting them know that their entry was saved || sent to admin || an error occurred while processing, regardless, when this is resolved the user should only see one button at the bottom of the page to take them bakc to their individual landing page

# Tasks:

- [ ] Create basic structure for beginning `Supply Pick-Up Report` Form Component
- [ ] Check Router syntax is fully functional from `Individual Volunteer` Component to `Supply Pick-Up Report` Component
- [ ] Top of the Page Should read, "Supply Pick-Up Report Form"
- [ ] `Label` with the `input` place holder "shift" and another `input` and place holder that says "date"
- [ ] Labels and input lines for the following categories, possibly more as needed:
     - [ ] weight
     - [ ] type
     - [ ] baked goods
     - [ ] frozen prepared
     - [ ] fresh prepared 
     - [ ] non-perishables
     - [ ] dairy
     - [ ] meat
     - [ ] produce
     - [ ] other (other will have its own additional data entry input line to create the label for the corresponding entry)
- [ ] Check box or radio button for: weighed with scale || Guesstimate
- [ ] Time Spent label, with numbers down to decimal of hours spent 
- [ ] Big input box that allows folx to leave notes about the pick up 
- [ ] One last check box to flag their entry for review of admin
- [ ] Two buttons, one to go to their individual home page, one to submit the form
- [ ] error handling and conditional rendering for for form submission success or delay
- [ ] after form submission only one button remains, the `return home` with a thank you note to the user for submitting
- [ ] Add API fetch for POST/PATCH
- [ ] Test new component with Cypress
- [ ] Test Routing with Cypress
- [ ] Give Code a Review and Refactor to verify that all codes present are at optimal efficiency

# Additional Notes to Reviewers

Let me know if any of the information is incomplete or unclear. Also, if you have suggestions on things to add, please comment with suggestions!
